### ISSUE TITLE
Command-line: encoding error with utf-8 file

### ISSUE THREAD

**Issue by ColinMaudry** [theodi/csvlint.rb#170]
With [bano-04.csv](https://github.com/theodi/csvlint.rb/files/36951/bano-04.txt), I'm trying to validate is with a CSVW schema using csvlint in command line.

I wanted to start simple, without a schema, so I ran:

```
csvlint bano-04.csv
```

And I got the following error:

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/csvlint-0.2.6/lib/csvlint/csvw/number_format.rb:12: invalid multibyte char (US-ASCII) (SyntaxError)
/var/lib/gems/1.9.1/gems/csvlint-0.2.6/lib/csvlint/csvw/number_format.rb:12: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/csvlint-0.2.6/lib/csvlint/csvw/number_format.rb:12: syntax error, unexpected $end, expecting ')'
...}[0-9]+)?([Ee][-+]?[0-9]+)?[%‰]?)|NaN|INF|-INF)$")
...                               ^
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/csvlint-0.2.6/lib/csvlint.rb:20:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/csvlint-0.2.6/lib/csvlint/cli.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/csvlint-0.2.6/bin/csvlint:4:in `<top (required)>'
	from /usr/local/bin/csvlint:23:in `load'
	from /usr/local/bin/csvlint:23:in `<main>'
```

It's worth noticing that this simple validation works well on csvlint.io, with just 2 messages reporting that there is no way to know whether my file has a header row, and that newlines are the wrong ones (not Windows-like).

**Comment by EdwinRozario** [comment]
+1

**Comment by Zideng** [comment]
+1
