### ISSUE TITLE
Quoted CRs in CRLF file incorrectly result in validation errors

### ISSUE THREAD

**Issue by andylolz** [theodi/csvlint.rb#198]
So e.g.

```
"Foo","Bsr","Baz"^M
"Biff","Baff","Boff
"^M
"Qux","Teaspoon","Doge"^M
```

…results in:

```
$ csvlint test.csv
.!.
test.csv is INVALID
1. unclosed_quote. Row: 2. "Biff","Baff","Boff
"
```

According to the [RFC 4180](https://tools.ietf.org/html/rfc4180), though, I think this should be fine.

**Comment by andylolz** [comment]
By default, the type of line endings used are auto-detected:
https://github.com/theodi/csvlint.rb/blob/873617f5/lib/csvlint/validate.rb#L302

…but the CSV is parsed row-by-row:
https://github.com/theodi/csvlint.rb/blob/873617f5/lib/csvlint/validate.rb#L182

So in the case described above, auto-detect gets it wrong.

```ruby
irb(main):001:0> require 'csv'
=> true
irb(main):002:0> # load the data above
irb(main):003:0* contents = ["Foo,Bsr,Baz\r\n", "Biff,Baff,\"Boff\n", "\"\r\n", "Qux,Teaspoon,Doge\r\n"]
=> ["Foo,Bsr,Baz\r\n", "Biff,Baff,\"Boff\n", "\"\r\n", "Qux,Teaspoon,Doge\r\n"]
irb(main):004:0> 
irb(main):005:0* # try to parse the second row, auto-detecting line endings
irb(main):006:0* CSV.parse_line(contents[1] + contents[2], {:row_sep => :auto})
CSV::MalformedCSVError: Unclosed quoted field on line 1.
  from …/csv.rb:1872:in `block in shift'
  from …/csv.rb:1779:in `loop'
  from …/csv.rb:1779:in `shift'
  from …/csv.rb:1310:in `parse_line'
  from (irb):6
  from …/irb:11:in `<main>'
irb(main):007:0> 
irb(main):008:0* # try to parse the second row, manually specifying '\r\n' line endings
irb(main):009:0* CSV.parse_line(contents[1] + contents[2], {:row_sep => '\r\n'})
=> ["Biff", "Baff", "Boff\n"]
```

**Comment by andylolz** [comment]
I guess the solution would be to set `row_sep` to [`@line_breaks`](https://github.com/theodi/csvlint.rb/blob/873617f5/lib/csvlint/validate.rb#L326-L332) or something like that.

**Comment by Floppy** [comment]
Ah yes, @jenit and I were discussing this the other day, and we wondered if it was because of mixed line breaks as you've found. I think your solution will probably work; I need to check what the line-break behaviour inside quotes *should* be as well.

**Comment by andylolz** [comment]
I realised I should be explicit that parsing the whole thing with auto-detect line endings switched on works fine:

```ruby
irb(main):009:0* CSV.parse(contents.join, {:row_sep => :auto})
=> [["Foo", "Bsr", "Baz"], ["Biff", "Baff", "Boff\n"], ["Qux", "Teaspoon", "Doge"]]
```

So this is only an issue when parsing row-by-row.

**Comment by kspurgin** [comment]
I have run into this same issue or a very similar one. Behavior of Csvlint and stdlib CSV parse documented [here](https://gist.github.com/kspurgin/693b8e1b3d2f4944960c92eab3ec1a90#tests-more-current-versions). (Test structure described [here](https://gist.github.com/kspurgin/693b8e1b3d2f4944960c92eab3ec1a90#tests-csv-importer-environmentversions))

**Comment by kspurgin** [comment]
The contributing guidelines say: "Before you start coding, please reach out to us either on our [gitter channel](https://gitter.im/theodi/toolbox) or by tagging a repository administrator on the issue ticket you are interested in contributing towards to indicate your interest in helping."

I am not finding a list of the repository admins, and apparently I need push access to a repo to get that info from GitHub API, so I'm making assumptions based on who has merged all recent PRs and tagging @Floppy here to indicate that I'd like to attempt a fix for this issue.

Rationale/use case/background: 

We use csvlint in [a batch data import application](https://github.com/collectionspace/collectionspace-csv-importer) to validate user-generated CSVs before allowing import of data in the files. Using csvlint to prevent the import of CSVs with issues like ragged rows, invalid encoding, and stray/unclosed quotes is important to prevent clients from inadvertently loading malformed data. 

This issue is currently blocking some of our clients from importing valid CSVs with mixed EOL characters inside quoted values (an artifact of original data source, and what OS they used to prepare the data, apparently). If you export data from our application as CSV on a Windows machine for roundtripping via our import tool, you get mixed EOL characters and can't re-ingest the data because csvlint flags the CSV as invalid. Our users are primarily collection managers in GLAM institutions, not data wrangling/tech savvy people; they are going to tune out/give up if anyone starts explaining CR, LF, vs CRLF to them.

Mixed EOL characters are handled fine by the standard Ruby CSV library, and are not prohibited by [RFC 4180](https://tools.ietf.org/html/rfc4180) according to my reading, so csvlint flagging these as invalid needs to be fixed.

**Comment by kspurgin** [comment]
Hey, I solved this in two different ways, which can be examined here: https://github.com/kspurgin/csvlint.rb/pulls

I prefer [PR2](https://github.com/kspurgin/csvlint.rb/pull/2) as it feels more expressive of the actual problem, and less hacky than the other. 

From what I can tell, the root of the problem is: once we are at Validate.parse_contents, we have already gotten the item of interest down to a single line of the CSV. But we then call LineCSV on it, passing the row_sep: :auto option in many cases. LineCSV subclasses CSV, whose Parser does a terrible job determining the proper row separator from a single line if there are EOL characters inside quotes. 

If you let me know which of these is acceptable (if either is), I'll do a real PR with better commit messages.
